server:
  port: 8769
spring:
  application:
    name: mySpringCloud-zuul
zuul:
  routes:
    backend-admin:
      path: /backend/admin/**
      serviceId: mySpringCloud-web-admin
    backend-posts:
      path: /backend/posts/**
      serviceId: mySpringCloud-web-posts
