spring:
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    sentinel:
      master: mymaster
      nodes: 127.0.0.1:26379, 1127.0.0.1:26380, 127.0.0.1:26381
