spring:
  application:
    name: mySpringCloud-service-upload

server:
  port: 9100

fastdfs.base.url: http://192.168.75.128:8888/
storage:
  type: fastdfs
  fastdfs:
    tracker_server: 192.168.75.128:22122
